apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: node:18-alpine 
          ports:
            - containerPort: 3000
          