apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: 192636115768.dkr.ecr.us-east-1.amazonaws.com/ecr_repository:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: db-credentials