apiVersion: v1
kind: Service
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-image-updater
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer