
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - unzip
          - software-properties-common
          - ncdu
          - openjdk-17-jdk  # Ensure Java for Jenkins
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure pip3 is installed
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker SDK for Python is installed
      pip:
        name: docker
        executable: pip3

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
      when: ansible_os_family == "Debian"

    - name: Start and enable Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create Docker network
      docker_network:
        name: "{{ docker_network }}"
        state: present

    - name: Install Trivy
      shell: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      args:
        creates: /usr/local/bin/trivy
      when: ansible_os_family == "Debian"

    - name: Clean npm cache
      command: npm cache clean --force
      changed_when: false

    - name: Clean unused Docker images and volumes
      command: docker system prune -a --volumes --force
      changed_when: false

    - name: Clear temporary files
      command: rm -rf /tmp/*
      changed_when: false

    - name: Run PostgreSQL container for SonarQube
      docker_container:
        name: sonarqube_db
        image: postgres:latest
        state: started
        restart_policy: always
        networks:
          - name: "{{ docker_network }}"
        env:
          POSTGRES_USER: "{{ postgres_user }}"
          POSTGRES_PASSWORD: "{{ postgres_password }}"
          POSTGRES_DB: "{{ postgres_db }}"
        volumes:
          - sonarqube_db_data:/var/lib/postgresql/data

    - name: Run SonarQube container
      docker_container:
        name: sonarqube
        image: sonarqube:{{ sonarqube_version }}
        state: started
        restart_policy: always
        ports:
          - "{{ sonarqube_port }}:9000"
        networks:
          - name: "{{ docker_network }}"
        env:
          SONAR_JDBC_URL: "jdbc:postgresql://sonarqube_db:5432/{{ postgres_db }}"
          SONAR_JDBC_USERNAME: "{{ postgres_user }}"
          SONAR_JDBC_PASSWORD: "{{ postgres_password }}"
        volumes:
          - sonarqube_data:/opt/sonarqube/data
          - sonarqube_logs:/opt/sonarqube/logs
          - sonarqube_extensions:/opt/sonarqube/extensions

    - name: Install SonarQube scanner
      npm:
        name: sonar-scanner
        global: yes
        state: present

    - name: Ensure project directory exists
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Configure sonar-project.properties
      copy:
        dest: "{{ project_dir }}/sonar-project.properties"
        content: |
          sonar.projectKey=my-node-app
          sonar.projectName=Node App
          sonar.sources=Application
          sonar.exclusions=node_modules/**,dist/**
          sonar.host.url=http://44.199.248.237:9000
          {% if sonar_token %}
          sonar.token={{ sonar_token }}
          {% endif %}
          sonar.language=js
        mode: '0644'

    - name: Ensure Jenkins directory permissions
      file:
        path: /var/lib/jenkins
        owner: jenkins
        group: jenkins
        recurse: yes
      when: ansible_os_family == "Debian"

    - name: Create cron job for daily cleanup
      cron:
        name: "Daily disk cleanup"
        minute: "0"
        hour: "2"
        job: "/usr/bin/docker system prune -a --volumes --force && /usr/bin/npm cache clean --force && rm -rf /tmp/*"
      when: ansible_os_family == "Debian"