config:
  logLevel: debug  


  registries:
    - name: DockerHub
      api_url: https://index.docker.io/v1/
      prefix: docker.io
      ping: yes
      credentials: secret:dockerhub-creds

rbac:
  create: true

serviceAccount:
  create: true
  name: argocd-image-update

imageUpdater:
  enabled: true

# Update values.yml to make monitoring
server:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        release: monitoring

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        release: monitoring

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        release: monitoring

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    additionalLabels:
      release: monitoring